name = "sockcoin"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]


[vars]
SK_ESTOKEN="VZF13T4M4NCUJF1M46BG4Q66EHY3SZFC7Y"
SK_EXCKEY='6c15c49ccf84b892391a9e8d'
SK_CMCKEY="d15bcfdf-9b59-4f4c-8296-dffd8f77d89d"
